options:
  prev_tag: "versio-prev"

projects:
  - name: "glider-macros"
    id: 1
    tag_prefix: ""
    labels: cargo
    changelog: "CHANGELOG.html"
    version:
      file: "Cargo.toml"
      toml: "package.version"
    hooks:
      post_write: 'cargo update --workspace'

sizes:
  use_angular: true
  fail: ["*"]
